version: '3.7'
services:
    apache:
      build:
        dockerfile: php7-apache2-dockerfile
        context: .      
      container_name: php7-apache2
      restart: always
      ports:
        - '80:80'
      volumes:
        - ./checklist:/var/www/html
      depends_on:
        - mysqldb
      links:
        - mysqldb

    mysqldb:
      container_name: mysqchecklist
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      hostname: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: checklist
      volumes:
          - ./mysql:/var/lib/mysql
      tty: true
      ports:
          - 3306:3306